GET http://localhost:3000/workouts

###


GET http://localhost:3000/maxWeight/michael/456

###

PATCH http://localhost:3000/maxWeight/6613a2c5a8ba9ce9e3d76578
Content-Type: application/json

{
    "workoutID": "123",
    "exerciseID": "456",
    "userID": "michael",
    "maxWeight": 160,
    "weightUnit": "lbs"
}


####

POST http://localhost:3000/maxWeight
Content-Type: application/json

{ 
    "workoutID": "123",
    "exerciseID": "456",
    "userID": "michael",
    "weight": 150,
    "weightUnit": "lbs"
}

###

PATCH http://localhost:3000/workouts/complete/6612bacf509fe9cfb1f1bfda

###

DELETE http://localhost:3000/sets/6611120478ceedf6a79c30ee

###

GET http://localhost:3000/exercises

###

POST http://localhost:3000/exercises
Content-Type: application/json

{
    "name": "Bench Press",
    "userID": "60a1c5f0a5d4f8a0b8c9d1e2",
    "primaryMuscleGroup": "Chest",
    "secondaryMuscleGroup": "Triceps"
}

###
GET http://localhost:3000/users/660b813e8c177e9c70cf2776

###

GET http://localhost:3000/users/username/MrKocherrrr

###


PATCH http://localhost:3000/users/660bad5fa1e3c5eb5ec31c7d
Content-Type: application/json

{
    "username": "Mr Kocherrrr"
}